### 单数据源无事务抛错(ds1)
GET http://localhost:8080/ds/tx/off/throw

### 单数据源有事务抛错(ds2)
GET http://localhost:8080/ds/tx/on/throw

### 单数据源有事务不抛错(ds2)
GET http://localhost:8080/ds/tx/on

### 多数据源无事务抛错([ds1] [ds2 throw])
GET http://localhost:8080/ds/tx/mix/off/throw

### 多数据源无事务不抛错([ds1] [ds2])
GET http://localhost:8080/ds/tx/mix/off

### 多数据源有事务不抛错([ds1] [ds2])
GET http://localhost:8080/ds/tx/mix/on

### 多数据源有事务抛错([ds1] [ds2 throw])
GET http://localhost:8080/ds/tx/mix/on/throw